# fly.toml app configuration file generated for seo-tool on 2024-08-02T16:19:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seo-tool'
primary_region = 'ewr'
[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[mounts]]
  source = "seo_tool_volume"
  destination = "/volume"

[[vm]]
cpu_kind = "shared"
cpu_cores = 1
memory_mb = 1024
